/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'not-found': RouteRecordInfo<
      'not-found',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    'about': RouteRecordInfo<
      'about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'home': RouteRecordInfo<
      'home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'learning': RouteRecordInfo<
      'learning',
      '/learning',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'vue3': RouteRecordInfo<
      'vue3',
      '/learning/vue3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'settings': RouteRecordInfo<
      'settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'menu_setting': RouteRecordInfo<
      'menu_setting',
      '/settings/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'role_setting': RouteRecordInfo<
      'role_setting',
      '/settings/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ui-component': RouteRecordInfo<
      'ui-component',
      '/ui-components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'button': RouteRecordInfo<
      'button',
      '/ui-components/button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'icon': RouteRecordInfo<
      'icon',
      '/ui-components/icon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'table': RouteRecordInfo<
      'table',
      '/ui-components/table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'table-details': RouteRecordInfo<
      'table-details',
      '/ui-components/table/details/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/[...404].vue': {
      routes:
        | 'not-found'
      views:
        | never
    }
    'src/views/about/index.vue': {
      routes:
        | 'about'
      views:
        | never
    }
    'src/views/home/index.vue': {
      routes:
        | 'home'
      views:
        | never
    }
    'src/views/learning/index.vue': {
      routes:
        | 'learning'
      views:
        | never
    }
    'src/views/learning/vue3/index.vue': {
      routes:
        | 'vue3'
      views:
        | never
    }
    'src/views/settings/index.vue': {
      routes:
        | 'settings'
      views:
        | never
    }
    'src/views/settings/menu.vue': {
      routes:
        | 'menu_setting'
      views:
        | never
    }
    'src/views/settings/role.vue': {
      routes:
        | 'role_setting'
      views:
        | never
    }
    'src/views/ui-components/index.vue': {
      routes:
        | 'ui-component'
      views:
        | never
    }
    'src/views/ui-components/button/index.vue': {
      routes:
        | 'button'
      views:
        | never
    }
    'src/views/ui-components/icon/index.vue': {
      routes:
        | 'icon'
      views:
        | never
    }
    'src/views/ui-components/table/index.vue': {
      routes:
        | 'table'
      views:
        | never
    }
    'src/views/ui-components/table/details/[id].vue': {
      routes:
        | 'table-details'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
