/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'not-found': RouteRecordInfo<
      'not-found',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    'home': RouteRecordInfo<
      'home',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sysFunc': RouteRecordInfo<
      'sysFunc',
      '/sysFunc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'multiMenus': RouteRecordInfo<
      'multiMenus',
      '/sysFunc/multiMenus',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'menu1': RouteRecordInfo<
      'menu1',
      '/sysFunc/multiMenus/menu1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'menu2': RouteRecordInfo<
      'menu2',
      '/sysFunc/multiMenus/menu2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'request': RouteRecordInfo<
      'request',
      '/sysFunc/request',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'sysMgmt': RouteRecordInfo<
      'sysMgmt',
      '/sysMgmt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'codemapSettings': RouteRecordInfo<
      'codemapSettings',
      '/sysMgmt/codemapSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'menuSettings': RouteRecordInfo<
      'menuSettings',
      '/sysMgmt/menuSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'userSettings': RouteRecordInfo<
      'userSettings',
      '/sysMgmt/userSettings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/[...404].vue': {
      routes:
        | 'not-found'
      views:
        | never
    }
    'src/views/home/index.vue': {
      routes:
        | 'home'
      views:
        | never
    }
    'src/views/sysFunc/index.vue': {
      routes:
        | 'sysFunc'
      views:
        | never
    }
    'src/views/sysFunc/multiMenus/index.vue': {
      routes:
        | 'multiMenus'
      views:
        | never
    }
    'src/views/sysFunc/multiMenus/menu1/index.vue': {
      routes:
        | 'menu1'
      views:
        | never
    }
    'src/views/sysFunc/multiMenus/menu2/index.vue': {
      routes:
        | 'menu2'
      views:
        | never
    }
    'src/views/sysFunc/request/index.vue': {
      routes:
        | 'request'
      views:
        | never
    }
    'src/views/sysMgmt/index.vue': {
      routes:
        | 'sysMgmt'
      views:
        | never
    }
    'src/views/sysMgmt/codemapSettings/index.vue': {
      routes:
        | 'codemapSettings'
      views:
        | never
    }
    'src/views/sysMgmt/menuSettings/index.vue': {
      routes:
        | 'menuSettings'
      views:
        | never
    }
    'src/views/sysMgmt/userSettings/index.vue': {
      routes:
        | 'userSettings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
