/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'not-found': RouteRecordInfo<'not-found', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    'about': RouteRecordInfo<'about', '/about', Record<never, never>, Record<never, never>>,
    'home': RouteRecordInfo<'home', '/home', Record<never, never>, Record<never, never>>,
    'learning': RouteRecordInfo<'learning', '/learning', Record<never, never>, Record<never, never>>,
    'vue3': RouteRecordInfo<'vue3', '/learning/vue3', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
    'menu_setting': RouteRecordInfo<'menu_setting', '/settings/menu', Record<never, never>, Record<never, never>>,
    'role_setting': RouteRecordInfo<'role_setting', '/settings/role', Record<never, never>, Record<never, never>>,
    'ui-component': RouteRecordInfo<'ui-component', '/ui-components', Record<never, never>, Record<never, never>>,
    'button': RouteRecordInfo<'button', '/ui-components/button', Record<never, never>, Record<never, never>>,
    'icon': RouteRecordInfo<'icon', '/ui-components/icon', Record<never, never>, Record<never, never>>,
    'table': RouteRecordInfo<'table', '/ui-components/table', Record<never, never>, Record<never, never>>,
    'table-details': RouteRecordInfo<'table-details', '/ui-components/table/details/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
